id = "plantuml"
name = "PlantUML"
version = "0.1.0"
schema_version = 1
authors = ["Gabriel Silva <gabe@gabe.id>"]
description = "PlantUML support."
repository = "https://github.com/gabeidx/zed-plantuml"

[grammars.plantuml]
repository = "https://github.com/Szeliga/tree-sitter-plantuml"
commit = "a3cfbf844d727b077f0070769e6d1c0977cc58f9"
